logger:
  type: stdout
  level: INFO

core:
  threads: 2
  runMode: once
  #runMode: repeat
  #sleepDuration: 30

common:
  github:
    rate_limit_wait_max: 120
    #username: name
    #password: password or pat

sources:
  - type: inline
    watchers:
      - name: PythonAlpineImage
        type: docker_registry
        repo: registry-1.docker.io
        image: python
        tag: 3.7.2-alpine3.8
        includes:
          - 3\.[7-9]\.[0-9]+-alpine3\.8
        excludes:
          - .*rc[0-9]*-.*
          - .*[ab][1-9]-.*
      - name: PyYAML PyPI
        type: pypi
        package: PyYAML
        version: 5.1
        includes:
          - 5\..*
        excludes:
          - .*[ab][1-9]$
      - name: TestGogs
        type: raw_html
        page_url: https://try.gogs.io/gogs/gogs/commits/master
        id: 6bd08a0b6f
        container_selector: "#commits-table"
        item_selector: "tbody tr"
        id_selector: "[class~=sha]"
        id_attribute: ""
        date_selector: "[class~=time-since]"
        date_attribute: "title"
        reverse: False
        basic_auth:
          username: your_username
          password: your_username
  - type: file
    path: github_watchers.yaml

outputs:
  - type: yaml_file
    path: out.yaml
    displayUpToDate: yes
  - type: csv_file
    path: out.csv
    displayHeader: yes
    displayUpToDate: yes
  - type: prometheus_file
    path: out.prom
  - type: prometheus_http
    port: 8080
